language: java
jdk:
- oraclejdk8
after_success:
- "./gradlew build"
#- "./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG"
deploy:
  provider: heroku
  api_key: $DEPLOY_KEY    
  app: customer-ms-java
  on:
    repo: SOFT8025-msc/customer-ms-java
