language: java
jdk:
- oraclejdk8
after_success:
- "./gradlew build jacocoTestReport"
- "./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG"

